[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "globaltirh-utils"
version = "0.1.1"
description = "Repositório de Utilidades para Globaltirh"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "pyarrow",
    "Unidecode",
    "colorama",
    "python-dotenv",
    "pytz",
    "PyJWT[crypto]",
    "requests"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/GlobalTIRH-Enterprise/globaltirh-utils"
"Bug Tracker" = "https://github.com/GlobalTIRH-Enterprise/globaltirh-utils/issues"

[tool.setuptools.packages.find]
include = ["globaltirh_utils*"]
